version: 2
updates:
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "Asia/Kolkata"
  - package-ecosystem: "github-actions"
    directory: '/'
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "Asia/Kolkata"

