name: Build npm package
# Runs the workflow on the below events:
# 1. On push to the main branch.
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build_npm_package:
    runs-on: ubuntu-latest
    # Build ppm package job
    name: Build npm package
    steps:
        # Check out code
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        
        # Install node 
      - name: Set up node 20
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

        # Install node dependencies
      - name: Install dependencies
        run: npm ci

        # Build node project
      - name: Run npm build
        run: npm run build
        
      - name:  Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm package
          path: ./dist


