name: Build
on:
  push:
    branches: [main]

jobs:
  Build_npm_package:
    runs-on: ubuntu-latest
    name: Build npm package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up node 20
        uses: actions/setup-node@v4 
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      - name: Run npm build
        run: npm run build
          
      - uses: actions/upload-artifact@v4
        with:
          name: npm package
          path: ./dist
      # - name: Delete artifacts
      #   run: |
      #     rm -rf .github/workflows/artifacts/*
